---
title: "2014translation"
author: "Yuchen Huang"
date: "2023-10-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read Data
```{r}
library(tidyverse)
ZZ14 <- read.csv("perfil_eleitor_secao_2014_ZZ.csv", sep = ";")
#glimpse(ZZ14)
```

## Column Names
```{r}
col_name <- colnames(ZZ14)
colnames(ZZ14) <- c(
    "GENERATION_DATE",       # "DT_GERACAO"
    "GENERATION_TIME",       # "HH_GERACAO"
    "ELECTION_YEAR",         # "ANO_ELEICAO"
    "STATE_CODE",            # "SG_UF"
    "CITY_CODE",             # "CD_MUNICIPIO"
    "CITY_NAME",             # "NM_MUNICIPIO"
    "CITY_BIOMETRIC_CODE",   # "CD_MUN_SIT_BIOMETRICA"
    "CITY_BIOMETRIC_STATUS", # "DS_MUN_SIT_BIOMETRICA"
    "ZONE_NUMBER",           # "NR_ZONA"
    "SECTION_NUMBER",        # "NR_SECAO"
    "VOTING_PLACE_NUMBER",   # "NR_LOCAL_VOTACAO"
    "GENDER_CODE",           # "CD_GENERO"
    "GENDER",                # "DS_GENERO"
    "MARITAL_STATUS_CODE",   # "CD_ESTADO_CIVIL"
    "MARITAL_STATUS",        # "DS_ESTADO_CIVIL"
    "AGE_GROUP_CODE",        # "CD_FAIXA_ETARIA"
    "AGE_GROUP",             # "DS_FAIXA_ETARIA"
    "EDUCATION_LEVEL_CODE",  # "CD_GRAU_ESCOLARIDADE"
    "EDUCATION_LEVEL",       # "DS_GRAU_ESCOLARIDADE"
    "NUMBER_OF_VOTERS_PROFILE",   # "QT_ELEITORES_PERFIL"
    "NUMBER_OF_BIOMETRIC_VOTERS", # "QT_ELEITORES_BIOMETRIA"
    "NUMBER_OF_VOTERS_WITH_DISABILITIES", # "QT_ELEITORES_DEFICIENCIA"
    "NUMBER_OF_VOTERS_WITH_SOCIAL_NAME"  # "QT_ELEITORES_INC_NM_SOCIAL"
    )
```

```{r}
city_name <- unique(ZZ14$CITY_NAME)
city_name_t <- c(
  "OIZUMI-JAPA" = "OIZUMI-JAPAN",
  "OSLO-NORG" = "OSLO-NORWAY",
  "OTTAWA-CANA" = "OTTAWA-CANADA",
  "PANAM\xc1-PANA" = "PANAMA CITY-PANAMA",
  "PARAMARIBO-SURI" = "PARAMARIBO-SURINAME",
  "PARIS-FRAN" = "PARIS-FRANCE",
  "PASO LOS LIBRES-ARGT" = "PASO LOS LIBRES-ARGENTINA",
  "PEDRO CABALLERO-PARG" = "PEDRO CABALLERO-PARAGUAY",
  "PEQUIM-CHIN" = "BEIJING-CHINA",
  "PORT OF SPAIN-TTOB" = "PORT OF SPAIN-TRINIDAD AND TOBAGO",
  "PORTO PR\xcdNCIPE-HAIT" = "PORT AU PRINCE-HAITI",
  "PORTO-PORT" = "PORTO-PORTUGAL",
  "PRAGA-TCHE" = "PRAGUE-CZECH REPUBLIC",
  "PRAIA-CABO" = "PRAIA-CAPE VERDE",
  "PRET\xd3RIA-RAFS" = "PRETORIA-SOUTH AFRICA",
  "PUERTO SUAREZ-BOLI" = "PUERTO SUAREZ-BOLIVIA",
  "QUITO-EQUA" = "QUITO-ECUADOR",
  "RABAT-MARR" = "RABAT-MOROCCO",
  "RAMALLAH-PALE" = "RAMALLAH-PALESTINE",
  "RIADE-ARAB" = "RIYADH-SAUDI ARABIA",
  "RIO BRANCO-URUG" = "RIO BRANCO-URUGUAY",
  "ROMA-ITAL" = "ROME-ITALY",
  "ROTERD\xc3-HOLA" = "ROTTERDAM-NETHERLANDS",
  "SALTOS DO GUAIRA-PARG" = "SALTOS DO GUAIRA-PARAGUAY",
  "STA C LA SIERRA-BOLI" = "SANTA CRUZ DE LA SIERRA-BOLIVIA",
  "SANTIAGO-CHIL" = "SANTIAGO-CHILE",
  "S\xc3O DOMINGOS-RDOM" = "SANTO DOMINGO-DOMINICAN REPUBLIC",
  "S\xc3O FRANCISCO-EUA" = "SAN FRANCISCO-USA",
  "S\xc3O JOS\xc9-RICA" = "SAN JOSE-COSTA RICA",
  "S\xc3O SALVADOR-ELSA" = "SAN SALVADOR-EL SALVADOR", #not sure
  "SEUL-CORS" = "SEOUL-SOUTH KOREA", #not sure
  "S\xd3FIA-BULG" = "SOFIA-BULGARIA",
  "SUZUKA-JAPA" = "SUZUKA-JAPAN",
  "SYDNEY-AUST" = "SYDNEY-AUSTRALIA",
  "TAIP\xc9-TAIW" = "TAIPEI-TAIWAN",
  "TAKAOKA-JAPA" = "TAKAOKA-JAPAN",
  "TEER\xc3-IRAN" = "TEHRAN-IRAN",
  "TEGUCIGALPA-HOND" = "TEGUCIGALPA-HONDURAS",
  "TEL AVIV-ISRA" = "TEL AVIV-ISRAEL",
  "T\xd3QUIO-JAPA" = "TOKYO-JAPAN",

  "TORONTO-CANA" = "TORONTO-CANADA",
  "TOYOHASHI-JAPA" = "TOYOHASHI-JAPAN",
  "GABORONE-BTWA" = "GABORONE-BOTSWANA",
  "TR\xcdPOLI-LBIA" = "TRIPOLI-LIBYA",
  "TUNIS-TUNI" = "TUNIS-TUNISIA",
  "UEDA-JAPA" = "UEDA-JAPAN",
  "VARS\xd3VIA-POLO" = "WARSAW-POLAND",
  "VIENA-OSTE" = "VIENNA-AUSTRIA",
  "WASHINGTON-EUA" = "WASHINGTON-USA",
  "WELLINGTON-NZEL" = "WELLINGTON-NEW ZEALAND",
  "WINDHOEK-NAMI" = "WINDHOEK-NAMIBIA",
  "XANGAI-CHIN" = "SHANGHAI-CHINA",
  "ZURIQUE-SUIC" = "ZURICH-SWITZERLAND",
  "DONGGUAN-CHIN" = "DONGGUAN-CHINA",
  "HARTFORD-EUA" = "HARTFORD-USA",
  "LUANDA-ANGO" = "LUANDA-ANGOLA",
  "MADRI-ESPA" = "MADRID-SPAIN",
  "MAN\xc1GUA-NICA" = "MANAGUA-NICARAGUA",
  "MANILA-FILI" = "MANILA-PHILIPPINES",
  "MAPUTO-MO\xc7A" = "MAPUTO-MOZAMBIQUE",
  "M\xc9XICO-MEXI" = "MEXICO CITY-MEXICO",
  "MIAMI-EUA" = "MIAMI-USA",
  "MIL\xc3O-ITAL" = "MILAN-ITALY",
  "MITSUKAIDO-JAPA" = "MITSUKAIDO-JAPAN",
  "MONTEVID\xc9U-URUG" = "MONTEVIDEO-URUGUAY",
  "MONTREAL-CANA" = "MONTREAL-CANADA",
  "MOSCOU-RUSS" = "MOSCOW-RUSSIA",
  "MUMBAI-INDI" = "MUMBAI-INDIA",
  "MUNIQUE-RFA" = "MUNICH-GERMANY",
  "NAGOYA-JAPA" = "NAGOYA-JAPAN",
  "NAIROBI-QUEN" = "NAIROBI-KENYA",
  "NOVA DELHI-INDI" = "NEW DELHI-INDIA",
  "NOVA YORK-EUA" = "NEW YORK-USA",
  "BOSTON-EUA" = "BOSTON-USA",
  "BRIDGETOWN-BARB" = "BRIDGETOWN-BARBADOS",
  "BRUXELAS-BELG" = "BRUSSELS-BELGIUM",
  "BUCARESTE-ROME" = "BUCHAREST-ROMANIA",
  "BUDAPESTE-HUNG" = "BUDAPEST-HUNGARY",
  "BUENOS AIRES-ARGT" = "BUENOS AIRES-ARGENTINA",
  "CAIENA-GUIF" = "CAYENNE-FRENCH GUIANA",
  "CAIRO-EGIT" = "CAIRO-EGYPT",
  "CAMBERRA-AUST" = "CANBERRA-AUSTRALIA",
  "CARACAS-VENE" = "CARACAS-VENEZUELA",
  "CHICAGO-EUA" = "CHICAGO-USA",

  "CHU\xcd-URUG" = "CHUY-URUGUAY",
  "CIDADE DO CABO-RAFS" = "CAPE TOWN-SOUTH AFRICA",
  "CINGAPURA-CING" = "SINGAPORE-SINGAPORE",
  "CIUDAD DEL ESTE-PARG" = "CIUDAD DEL ESTE-PARAGUAY",
  "CIUDAD GUAYANA-VENE" = "CIUDAD GUAYANA-VENEZUELA",
  "COCHABAMBA-BOLI" = "COCHABAMBA-BOLIVIA",
  "CONCEPCI\xd3N-PARG" = "CONCEPCION-PARAGUAY",
  "COPENHAGUE-DINA" = "COPENHAGEN-DENMARK",

  "C\xd3RDOBA-ARGT" = "CORDOBA-ARGENTINA",
  "DACAR-SENE" = "DAKAR-SENEGAL",
  "DAMASCO-SIRI" = "DAMASCUS-SYRIA",
  "DILI-TIML" = "DILI-TIMOR LESTE",
  "DOHA-CATA" = "DOHA-QATAR",
  "DUBLIN-IRLS" = "DUBLIN-IRELAND",
  "ENCARNACI\xd3N-PARG" = "ENCARNACION-PARAGUAY",
  "ESTOCOLMO-SUEC" = "STOCKHOLM-SWEDEN",
  "FRANKFURT-RFA" = "FRANKFURT-GERMANY",
  "GENEBRA-SUIC" = "GENEVA-SWITZERLAND",
  "GEORGETOWN-GUIA" = "GEORGETOWN-GUYANA",
  "GUATEMALA-GUAT" = "GUATEMALA CITY-GUATEMALA",
  "HAMAMATSU-JAPA" = "HAMAMATSU-JAPAN",
  "HAN\xd3I-VIET" = "HANOI-VIETNAM",
  "HARARE-ZIMB" = "HARARE-ZIMBABWE",
  "HAVANA-CUBA" = "HAVANA-CUBA",
  
  "HELSINQUE-FINL" = "HELSINKI-FINLAND",        
  "HONG KONG-HONG" = "HONG KONG-HONG KONG",        
  "HOUSTON-EUA" = "HOUSTON-USA",            
  "IAUND\xca-CAME" = "YAOUNDÉ-CAMEROON",
  "IQUITOS-PERU",           
  "IQUITOS-PERU" = "IQUITOS-PERU",
  "JACARTA-INDO" = "JAKARTA-INDONESIA",           
  "KIEV-UCRA" = "KIEV-UKRAINE",
  
  "KINGSTON-JAMA" = "KINGSTON-JAMAICA",
  "KINSHASA-RCON" = "KINSHASA-DEMOCRATIC REPUBLIC OF CONGO",
  "KUAITE-KUAI" = "KUWAIT-KUWAIT",
  "KUALA LUMPUR-MALA" = "KUALA LUMPUR-MALAYSIA",
  "LA PAZ-BOLI" = "LA PAZ-BOLIVIA",
  "LAGOS-NIGR" = "LAGOS-NIGERIA",
  "LIBREVILLE-GABA" = "LIBREVILLE-GABON",
  "LIMA-PERU" = "LIMA-PERU",
  "LISBOA-PORT" = "LISBON-PORTUGAL",
  "LOM\xc9-TOGO" = "LOME-TOGO",
  "LONDRES-GBRE" = "LONDON-UNITED KINGDOM",
  "LOS ANGELES-EUA" = "LOS ANGELES-USA",
  "ABIDJAN-COTE" = "ABIDJAN-COTE D'IVOIRE",
  "ABU DHABI-EAU" = "ABU DHABI-UNITED ARAB EMIRATES",
  "ACCRA-GANA" = "ACCRA-GHANA",
  "AM\xc3-JORD" = "AMMAN-JORDAN",
  "ANCARA-TURQ" = "ANKARA-TURKEY",
  "ARGEL-ARGL" = "ALGIERS-ALGERIA",
  "ARTIGAS-URUG" = "ARTIGAS-URUGUAY",
  "ASSUN\xc7\xc3O-PARG" = "ASUNCION-PARAGUAY",
  "ATENAS-GREC" = "ATHENS-GREECE",
  "BANGKOK-TAIL" = "BANGKOK-THAILAND",
  "BARCELONA-ESPA" = "BARCELONA-SPAIN",
  "BEIRUTE-LBAN" = "BEIRUT-LEBANON",
  "BELGRADO-SERV" = "BELGRADE-SERBIA",
  "BERLIM-RFA" = "BERLIN-GERMANY",
  "BISSAU-GUIB" = "BISSAU-GUINEA-BISSAU",
  "BOGOT\xc1-COLO" = "BOGOTA-COLOMBIA",
  "COLOMBO-SRIL" = "COLOMBO-SRI LANKA",
  "BELMOPAN-BELI" = "BELMOPAN-BELIZE",
  "CONACRI-GUIN" = "CONAKRY-GUINEA",
  "COTONOU-BENI" = "COTONOU-BENIN",
  "DAR ES SALAAM-TANZ" = "DAR ES SALAAM-TANZANIA",
  "IEREVAN-ARME" = "YEREVAN-ARMENIA",
  "MENDOZA-ARGT" = "MENDOZA-ARGENTINA",
  "ZAGREB-CROA" = "ZAGREB-CROATIA",
  "VANCOUVER-CANA" = "VANCOUVER-CANADA",
  "ATLANTA-EUA" = "ATLANTA-USA",
  "MASCATE-OM\xc3" = "MUSCAT-OMAN",
  "LIUBLIANA-ESVN" = "LJUBLJANA-SLOVENIA",
  "BRAZZAVILLE-CONG" = "BRAZZAVILLE-REPUBLIC OF CONGO",
  "BRATISLAVA-ESVK" = "BRATISLAVA-SLOVAKIA",
  "S\xc3O TOM\xc9-STPR" = "SAO TOME-SAO TOME AND PRINCIPE",
  "ASTANA-KAZA" = "ASTANA-KAZAKHSTAN",
  "MALABO-GNEQ" = "MALABO-EQUATORIAL GUINEA",
  "ISTAMBUL-TURQ" = "ISTANBUL-TURKEY",
  "NICOSIA-CYPR" = "NICOSIA-CYPRUS"
)

# Translating city names
ZZ14$CITY_NAME <- ifelse(ZZ14$CITY_NAME %in% names(city_name_t),
                         city_name_t[ZZ14$CITY_NAME],
                         ZZ14$CITY_NAME)
```

## Divide columns into two columns using "-"
```{r}
ZZ14 <- ZZ14 |>
  separate_wider_delim(cols = CITY_NAME,
                       delim = "-",
                       names = c("City", "Country"),
                       too_few = "error",
                       too_many = "merge")
```

## City Biometric status

```{r}
unique(ZZ14$CITY_BIOMETRIC_STATUS)
ZZ14$CITY_BIOMETRIC_STATUS <- "Without biometrics"
```

## Gender

```{r}
unique(ZZ14$GENDER)
ZZ14$GENDER <- ifelse(ZZ14$GENDER == "MASCULINO", "male", "female")
```

## Marital Status

```{r}
unique(ZZ14$MARITAL_STATUS)
ZZ14$MARITAL_STATUS[ZZ14$MARITAL_STATUS == "SOLTEIRO"] <- "SINGLE"
ZZ14$MARITAL_STATUS[ZZ14$MARITAL_STATUS == "CASADO"] <- "MARRIED"
ZZ14$MARITAL_STATUS[ZZ14$MARITAL_STATUS == "DIVORCIADO"] <- "DIVORCED"
ZZ14$MARITAL_STATUS[ZZ14$MARITAL_STATUS == "VI\xdaVO"] <- "WIDOWED"
ZZ14$MARITAL_STATUS[ZZ14$MARITAL_STATUS == "SEPARADO JUDICIALMENTE"] <- "LEGALLY SEPARATED"
ZZ14$MARITAL_STATUS[ZZ14$MARITAL_STATUS == "N\xc3O INFORMADO"] <- "NOT INFORMED"
```

## Education Level

```{r}
unique(ZZ14$EDUCATION_LEVEL)
ZZ14$EDUCATION_LEVEL[ZZ14$EDUCATION_LEVEL == "ENSINO M\xc9DIO INCOMPLETO"] <- "INCOMPLETE HIGH SCHOOL"
ZZ14$EDUCATION_LEVEL[ZZ14$EDUCATION_LEVEL == "ENSINO M\xc9DIO COMPLETO"] <- "HIGH SCHOOL GRADUATE"
ZZ14$EDUCATION_LEVEL[ZZ14$EDUCATION_LEVEL == "SUPERIOR INCOMPLETO"] <- "INCOMPLETE COLLEGE/UNIVERSITY"
ZZ14$EDUCATION_LEVEL[ZZ14$EDUCATION_LEVEL == "SUPERIOR COMPLETO"] <- "COLLEGE/UNIVERSITY GRADUATE"
ZZ14$EDUCATION_LEVEL[ZZ14$EDUCATION_LEVEL == "ENSINO FUNDAMENTAL COMPLETO"] <- "COMPLETE ELEMENTARY EDUCATION"
ZZ14$EDUCATION_LEVEL[ZZ14$EDUCATION_LEVEL == "ENSINO FUNDAMENTAL INCOMPLETO"] <- "INCOMPLETE ELEMENTARY EDUCATION"
ZZ14$EDUCATION_LEVEL[ZZ14$EDUCATION_LEVEL == "L\xca E ESCREVE"] <- "LITERATE (CAN READ AND WRITE)"
ZZ14$EDUCATION_LEVEL[ZZ14$EDUCATION_LEVEL == "ANALFABETO"] <- "ILLITERATE"
ZZ14$EDUCATION_LEVEL[ZZ14$EDUCATION_LEVEL == "N\xc3O INFORMADO" ] <- "NOT INFORMED"
```

## Age Group

```{r}
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "21 a 24 anos                  "] <- "21-24"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "25 a 29 anos                  "] <- "25-29"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "30 a 34 anos                  "] <- "30-34"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "35 a 39 anos                  "] <- "35-39"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "40 a 44 anos                  "] <- "40-44"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "65 a 69 anos                  "] <- "65-69"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "50 a 54 anos                  "] <- "50-54"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "55 a 59 anos                  "] <- "55-59"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "75 a 79 anos                  "] <- "75-79"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "60 a 64 anos                  "] <- "60-64"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "70 a 74 anos                  "] <- "70-74"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "20 anos                       "] <- "20"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "45 a 49 anos                  "] <- "45-49"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "16 anos                       "] <- "16"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "18 anos                       "] <- "18"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "19 anos                       "] <- "19"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "90 a 94 anos                  "] <- "90-94"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "85 a 89 anos                  "] <- "85-89"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "19 anos                       "] <- "19"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "17 anos                       "] <- "17"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "80 a 84 anos                  "] <- "80-84"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "100 anos ou mais              "] <- "100+"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "95 a 99 anos                  "] <- "95-99"
ZZ14$AGE_GROUP[ZZ14$AGE_GROUP == "Inv\xe1lido                      "] <- "Invalid"
```

## write csv

```{r}
write.csv(ZZ14, file = "translated_ZZ14.csv", row.names = FALSE)
```