---
title: "Translation2022"
author: "Yuchen Huang" + "Yuta Tsukumo"
date: "2023-10-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read Data

```{r}
library(tidyverse)
ZZ22 <- read.csv("perfil_eleitor_secao_2022_ZZ.csv",　sep = ";")
#glimpse(ZZ22)
```

## Column Names

```{r}
col_name <- colnames(ZZ22)
colnames(ZZ22) <- c(
    "GENERATION_DATE",       # "DT_GERACAO"
    "GENERATION_TIME",       # "HH_GERACAO"
    "ELECTION_YEAR",         # "ANO_ELEICAO"
    "STATE_CODE",            # "SG_UF"
    "CITY_CODE",             # "CD_MUNICIPIO"
    "CITY_NAME",             # "NM_MUNICIPIO"
    "CITY_BIOMETRIC_CODE",   # "CD_MUN_SIT_BIOMETRICA"
    "CITY_BIOMETRIC_STATUS", # "DS_MUN_SIT_BIOMETRICA"
    "ZONE_NUMBER",           # "NR_ZONA"
    "SECTION_NUMBER",        # "NR_SECAO"
    "VOTING_PLACE_NUMBER",   # "NR_LOCAL_VOTACAO"
    "GENDER_CODE",           # "CD_GENERO"
    "GENDER",                # "DS_GENERO"
    "MARITAL_STATUS_CODE",   # "CD_ESTADO_CIVIL"
    "MARITAL_STATUS",        # "DS_ESTADO_CIVIL"
    "AGE_GROUP_CODE",        # "CD_FAIXA_ETARIA"
    "AGE_GROUP",             # "DS_FAIXA_ETARIA"
    "EDUCATION_LEVEL_CODE",  # "CD_GRAU_ESCOLARIDADE"
    "EDUCATION_LEVEL",       # "DS_GRAU_ESCOLARIDADE"
    "NUMBER_OF_VOTERS_PROFILE",   # "QT_ELEITORES_PERFIL"
    "NUMBER_OF_BIOMETRIC_VOTERS", # "QT_ELEITORES_BIOMETRIA"
    "NUMBER_OF_VOTERS_WITH_DISABILITIES", # "QT_ELEITORES_DEFICIENCIA"
    "NUMBER_OF_VOTERS_WITH_SOCIAL_NAME"  # "QT_ELEITORES_INC_NM_SOCIAL"
    )
```

## City Name

```{r}
city_name <- unique(ZZ22$CITY_NAME)
city_name_t <- c(
  "KATMANDU" = "KATHMANDU",
  "ABIDJ\xc3" = "ABIDJAN", 
  "ABU DHABI" = "ABU DHABI",
  "ACCRA" = "ACCRA",
  "AM\xc3" = "UNKNOWN", #Not sure
  "ANCARA" = "ANKARA",
  "ARGEL" = "ALGIERS",
  "ARTIGAS" = "ARTIGAS", 
  "ASSUN\xc7\xc3O" = "ASUNCION", #Not sure
  "LISBOA" = "LISBON",
  "NOVA YORK" = "NEW YORK",
  "OSLO" = "OSLO",
  "OTTAWA" = "OTTAWA",
  "PANAMA" = "PANAMA CITY",
  "PARAMARIBO" = "PARAMARIBO",
  
  
  "SARAJEVO" = "SARAJEVO",
  "BELMOPAN" = "BELMOPAN",
  "CONACRI" = "CONAKRY",
  "COTONOU" = "COTONOU",
  "DAR ES SALAAM" = "DAR ES SALAAM",
  "IEREVAN" = "YEREVAN",
  "MENDOZA" = "MENDOZA",
  "ZAGREB" = "ZAGREB",
  "VANCOUVER" = "VANCOUVER",
  "ATLANTA" = "ATLANTA",
  "S\xc3O FRANCISCO" = "SAN FRANCISCO", 
  "S\xc3O JOS\xc9" = "SAN JOSE", 
  "S\xc3O SALVADOR" = "SAN SALVADOR", 
  "SEUL" = "SEOUL",
  "S\xd3FIA" = "SOFIA", #Not sure
  "SYDNEY" = "SYDNEY",
  "MIL\xc3O" = "MILAN", #Not sure
  "NAG\xd3IA" = "NAGOYA", 
  "MADRI" = "MADRID",
  "MAN\xc1GUA" = "MANAGUA", #Not sure
  "MANILA" = "MANILA",
  "MAPUTO" = "MAPUTO",
  "MEXICO" = "MEXICO CITY",
  "MIAMI" = "MIAMI",
  "LONDRES" = "LONDON",
  "MASCATE" = "MUSCAT",
  "BAKU" = "BAKU",
  "LIUBLIANA" = "LJUBLJANA",
  "BRAZZAVILLE" = "BRAZZAVILLE",
  "BRATISLAVA" = "BRATISLAVA",
  "S\xc3O TOM\xc9" = "SAO TOME", 
  "ASTANA" = "NUR-SULTAN",
  "MALABO" = "MALABO",
  "UAGADUGU" = "OUAGADOUGOU",
  "ISTAMBUL" = "ISTANBUL",
  "NICOSIA" = "NICOSIA",
  "GUATEMALA" = "GUATEMALA CITY",
  "TBILISI" = "TBILISI",
  "TIRANA" = "TIRANA",
  
  "FARO" = "FARO",
  "SAINT JOHNS" = "SAINT JOHNS", #Not sure
  "PUERTO IGUAZ\xda" = "PUERTO IGUAZU", 
  "BAGD\xc1" = "BAGHDAD", 
  "NASSAU" = "NASSAU",
  "ABUJA" = "ABUJA",
  "COBIJA" = "COBIJA",
  "PUERTO QUIJARRO" = "PUERTO QUIJARRO",
  "RIVERA" = "RIVERA",
  "VATICANO" = "VATICAN CITY",
  "LUSACA" = "LUSAKA",
  "TALIN" = "TALLINN",
  "ADIS ABEBA" = "ADDIS ABABA",
  "ST GEORGES DE LOYAPOCK" = "SAINT-GEORGES-DE-L'OYAPOCK",
  "LILONGUE" = "LILONGWE",
  "BAMAKO" = "BAMAKO",
  "YANGON" = "YANGON",
  "CASTRIES" = "CASTRIES",
  "KINGSTON-JAMAICA" = "KINGSTON",
  "BAREIN" = "MANAMA",
  "T\xd3QUIO" = "TOKYO", 
  "MONTEVID\xc9U" = "MONTEVIDEO", 
  "MONTREAL" = "MONTREAL",
  "ATENAS" = "ATHENS",
  "BANGKOK" = "BANGKOK",
  "BARCELONA" = "BARCELONA",
  "PARIS" = "PARIS",
  "NAIR\xd3BI" = "NAIROBI", 
  "NOVA DELHI" = "NEW DELHI",
  "LOS ANGELES" = "LOS ANGELES",
  "BERLIM" = "BERLIN",
  "BISSAU" = "BISSAU",
  "BOGOT\xc1" = "BOGOTA", 
  "BOSTON" = "BOSTON",
  "PASO LOS LIBRES" = "PASO DE LOS LIBRES",
  "PEDRO JUAN CABALLERO" = "PEDRO JUAN CABALLERO",
  "PEQUIM" = "BEIJING",
  "PORT OF SPAIN" = "PORT OF SPAIN",
  "PORTO PR\xcdNCIPE" = "PORT-AU-PRINCE",
  "PORTO" = "PORTO",
  "TAIP\xc9" = "TAIPEI", #
  "TEER\xc3" = "TEHRAN", #Not sure
  "TEGUCIGALPA" = "TEGUCIGALPA",
  
  "TEL AVIV" = "TEL AVIV",
  "LUANDA" = "LUANDA",
  "BUENOS AIRES" = "BUENOS AIRES",
  "CAIENA" = "CAYENNE",
  "CAIRO" = "CAIRO",
  "CAMBERRA" = "CAMBERRA",
  "CARACAS" = "CARACAS",
  "CHICAGO" = "CHICAGO",
  "BEIRUTE" = "BEIRUT",
  "BELGRADO" = "BELGRADE",
  "LOM\xc9" = "LOME",
  "TORONTO" = "TORONTO",
  "MOSCOU" = "MOSCOW",
  "MUMBAI" = "MUMBAI",
  "MUNIQUE" = "MUNICH",
  "CANT\xc3O" = "GUANGZHOU", #Not sure
  "GABORONE" = "GABORONE",
  "TR\xcdPOLI" = "TRIPOLI", 
  "TUNIS" = "TUNIS",
  "VARS\xd3VIA" = "WARSAW", #Not sure
  "VIENA" = "VIENNA",
  "PRAGA" = "PRAGUE",
  "PRAIA" = "PRAIA",
  "PRET\xd3RIA" = "PRETORIA",
  "QUITO" = "QUITO",
  "WASHINGTON" = "WASHINGTON",
  "CHUY" = "CHUY",
  "CIDADE DO CABO" = "CAPE TOWN",
  "SINGAPURA" = "SINGAPORE",
  "CIUDAD DEL ESTE" = "CIUDAD DEL ESTE",
  "RABAT" = "RABAT",
  "RAMALLAH" = "RAMALLAH",
  "RIADE" = "RIYADH",
  "RIO BRANCO" = "RIO BRANCO",
  "ROMA" = "ROME",
  "WELLINGTON" = "WELLINGTON",
  "WINDHOEK" = "WINDHOEK",
  "XANGAI" = "SHANGHAI",
  "ZURIQUE" = "ZURICH",
  "DUBLIN" = "DUBLIN",
  "ENCARNACI\xd3N" = "ENCARNACION", 
  "ESTOCOLMO" = "STOCKHOLM",
  "FRANKFURT" = "FRANKFURT",
  "BRIDGETOWN" = "BRIDGETOWN",
  "BRUXELAS" = "BRUSSELS",
  "AMSTERD\xc3" = "AMSTERDAM", 
  "SALTO DEL GUAIR\xc1" = "SALTO DEL GUAIRA",
  "CIUDAD GUAYANA" = "CIUDAD GUAYANA",
  "COCHABAMBA" = "COCHABAMBA",
  "CONCEPCI\xd3N" = "CONCEPCION", 
  "COPENHAGUE" = "COPENHAGEN",
  "C\xd3RDOBA" = "CORDOBA", 
  "DACAR" = "DAKAR",
  "DAMASCO" = "DAMASCUS",
  "D\xcdLI" = "DILI", 
  "DOHA" = "DOHA",
  "BUCARESTE" = "BUCHAREST",
  "BUDAPESTE" = "BUDAPEST",
  "SANTA CRUZ DE LA SIERRA" = "SANTA CRUZ DE LA SIERRA",
  "SANTIAGO" = "SANTIAGO",
  "S\xc3O DOMINGOS" = "SANTO DOMINGO", 
  "HARTFORD" = "HARTFORD",
  "COLOMBO" = "COLOMBO",
  "GENEBRA" = "GENEVA",
  "GEORGETOWN" = "GEORGETOWN",
  "HAMAMATSU" = "HAMAMATSU",
  "HAN\xd3I" = "HANOI", 
  "HARARE" = "HARARE",
  "HAVANA" = "HAVANA",
  "HELSINQUE" = "HELSINKI",
  "HONG KONG" = "HONG KONG",
  "HOUSTON" = "HOUSTON",
  "IAUND\xca" = "DJIBOUTI", #Not sure
  "IQUITOS" = "IQUITOS",
  "ISLAMABADE" = "ISLAMABAD", 
  "JACARTA" = "JAKARTA", 
  "KIEV" = "KIEV",
  "KINSHASA" = "KINSHASA",
  "KUAITE" = "KUWAIT CITY",
  "KUALA LUMPUR" = "KUALA LUMPUR",
  "LA PAZ" = "LA PAZ",
  "LAGOS" = "LAGOS",
  "LIBREVILLE" = "LIBREVILLE",
  "LIMA" = "LIMA"
)

# Translating city names
ZZ22$CITY_NAME <- ifelse(ZZ22$CITY_NAME %in% names(city_name_t),
                         city_name_t[ZZ22$CITY_NAME],
                         ZZ22$CITY_NAME)

```

## Country Name
```{r}
city_country <- readxl::read_xlsx("City_Country.xlsx")

ZZ22 <- ZZ22 |>
  left_join(select(city_country, -CITY_NAME), by = "CITY_CODE")
```


## City Biometric status

```{r}
unique(ZZ22$CITY_BIOMETRIC_STATUS)
ZZ22$CITY_BIOMETRIC_STATUS <- "Without biometrics"
```

## Gender

```{r}
unique(ZZ22$GENDER)
ZZ22$GENDER <- ifelse(ZZ22$GENDER == "MASCULINO", "male", "female")
```

## Marital Status

```{r}
unique(ZZ22$MARITAL_STATUS)
ZZ22$MARITAL_STATUS[ZZ22$MARITAL_STATUS == "SOLTEIRO"] <- "SINGLE"
ZZ22$MARITAL_STATUS[ZZ22$MARITAL_STATUS == "CASADO"] <- "MARRIED"
ZZ22$MARITAL_STATUS[ZZ22$MARITAL_STATUS == "DIVORCIADO"] <- "DIVORCED"
ZZ22$MARITAL_STATUS[ZZ22$MARITAL_STATUS == "VIÚVO"] <- "WIDOWED"
ZZ22$MARITAL_STATUS[ZZ22$MARITAL_STATUS == "SEPARADO JUDICIALMENTE"] <- "LEGALLY SEPARATED"

```

## Education Level

```{r}
unique(ZZ22$EDUCATION_LEVEL)
ZZ22$EDUCATION_LEVEL[ZZ22$EDUCATION_LEVEL == "ENSINO M\xc9DIO INCOMPLETO"] <- "INCOMPLETE HIGH SCHOOL"
ZZ22$EDUCATION_LEVEL[ZZ22$EDUCATION_LEVEL == "ENSINO M\xc9DIO COMPLETO"] <- "HIGH SCHOOL GRADUATE"
ZZ22$EDUCATION_LEVEL[ZZ22$EDUCATION_LEVEL == "SUPERIOR INCOMPLETO"] <- "INCOMPLETE COLLEGE/UNIVERSITY"
ZZ22$EDUCATION_LEVEL[ZZ22$EDUCATION_LEVEL == "SUPERIOR COMPLETO"] <- "COLLEGE/UNIVERSITY GRADUATE"
ZZ22$EDUCATION_LEVEL[ZZ22$EDUCATION_LEVEL == "ENSINO FUNDAMENTAL COMPLETO"] <- "COMPLETE ELEMENTARY EDUCATION"
ZZ22$EDUCATION_LEVEL[ZZ22$EDUCATION_LEVEL == "ENSINO FUNDAMENTAL INCOMPLETO"] <- "INCOMPLETE ELEMENTARY EDUCATION"
ZZ22$EDUCATION_LEVEL[ZZ22$EDUCATION_LEVEL == "L\xca E ESCREVE"] <- "LITERATE (CAN READ AND WRITE)"
ZZ22$EDUCATION_LEVEL[ZZ22$EDUCATION_LEVEL == "ANALFABETO"] <- "ILLITERATE"
ZZ22$EDUCATION_LEVEL[ZZ22$EDUCATION_LEVEL == "N\xc3O INFORMADO" ] <- "NOT INFORMED"

```

## Age Group

```{r}
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "21 a 24 anos                  "] <- "21-24"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "25 a 29 anos                  "] <- "25-29"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "30 a 34 anos                  "] <- "30-34"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "35 a 39 anos                  "] <- "35-39"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "40 a 44 anos                  "] <- "40-44"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "65 a 69 anos                  "] <- "65-69"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "50 a 54 anos                  "] <- "50-54"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "55 a 59 anos                  "] <- "55-59"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "75 a 79 anos                  "] <- "75-79"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "60 a 64 anos                  "] <- "60-64"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "70 a 74 anos                  "] <- "70-74"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "20 anos                       "] <- "20"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "45 a 49 anos                  "] <- "45-49"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "16 anos                       "] <- "16"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "18 anos                       "] <- "18"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "19 anos                       "] <- "19"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "90 a 94 anos                  "] <- "90-94"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "85 a 89 anos                  "] <- "85-89"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "19 anos                       "] <- "19"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "17 anos                       "] <- "17"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "80 a 84 anos                  "] <- "80-84"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "100 anos ou mais              "] <- "100+"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "95 a 99 anos                  "] <- "95-99"
ZZ22$AGE_GROUP[ZZ22$AGE_GROUP == "Inv\xe1lido                      "] <- "17"
```

## write csv

```{r}
write.csv(ZZ22, file = "translated_ZZ22.csv", row.names = FALSE)
```

