---
title: "IDB_EDA"
author: "Yuta Tsukumo"
date: "2023-10-07"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
IDB <- read.csv("perfil_eleitor_secao_2022_ZZ.csv",　sep = ";")
# CSV file uses a delimiter other than a comma, so specify it using the sep parameter. 

table(IDB$NM_MUNICIPIO)

```

Data Check
```{r}
summary(IDB)

unique(IDB$SG_UF)
unique(IDB$CD_ESTADO_CIVIL)
unique(IDB$DS_ESTADO_CIVIL)
unique(IDB$CD_FAIXA_ETARIA)
unique(IDB$DS_FAIXA_ETARIA)
unique(IDB$NM_MUNICIPIO) # 181 cities
unique(IDB$CD_GRAU_ESCOLARIDADE) 
unique(IDB$DS_GRAU_ESCOLARIDADE)
unique(IDB$QT_ELEITORES_BIOMETRIA)
unique(IDB$QT_ELEITORES_DEFICIENCIA)
unique(IDB$QT_ELEITORES_INC_NM_SOCIAL)
```


Variable selection (exclude variables with only one value or duplicate) and change names of variables
```{r}
# variable selection
IDB_sub <- IDB |>
  select(-DT_GERACAO, -HH_GERACAO, -ANO_ELEICAO, -SG_UF, -CD_MUN_SIT_BIOMETRICA, -DS_MUN_SIT_BIOMETRICA, -NR_ZONA, -CD_GENERO, -DS_ESTADO_CIVIL, -DS_FAIXA_ETARIA, -DS_GRAU_ESCOLARIDADE)

# change names from Portuguese to English
IDB_sub <- IDB_sub |>
  rename(
    cd_muni = CD_MUNICIPIO,
    name_muni = NM_MUNICIPIO,
    num_sec = NR_SECAO,
    num_stat = NR_LOCAL_VOTACAO,
    sex = DS_GENERO,
    cd_marit = CD_ESTADO_CIVIL,
    cd_age = CD_FAIXA_ETARIA,
    cd_edu = CD_GRAU_ESCOLARIDADE,
    num_eligvote = QT_ELEITORES_PERFIL,
    num_eligbio = QT_ELEITORES_BIOMETRIA,
    num_eligdis = QT_ELEITORES_DEFICIENCIA,
    num_eligreq = QT_ELEITORES_INC_NM_SOCIAL
    )
```


Correct class of variables and create other variables
```{r}
# correct class of variables
IDB_sub <- IDB_sub |>
  mutate(cd_muni = as.factor(cd_muni),
         name_muni = as.factor(name_muni),
         sex = as.factor(sex),
         cd_marit = as.factor(cd_marit),
         cd_age = as.factor(cd_age),
         cd_edu = as.factor(cd_edu),
         )

# create another educational category
IDB_sub <- IDB_sub |>
  filter(!cd_edu == "0") |>   # remove samples without information regarding education
  mutate(educ_cat = if_else(cd_edu == 8, "College", if_else(cd_edu %in% c(7,6) , "Highshool", "Incomplete High School")))

# create another age category"age_cat1"
IDB_sub <- IDB_sub |>
  filter(!cd_age == "-3") |> # remove samples without information regarding age
  mutate(age_cat1 = if_else(cd_age %in% c(1600, 1700, 1800, 1900), "10s", if_else(cd_age %in% c(2000, 2124,  2529), "20s", ifelse(cd_age %in% c(3034, 3539), "30s", ifelse(cd_age %in% c(4044, 4549), "40s", ifelse(cd_age %in% c(5054, 5559), "50s", ifelse(cd_age %in% c(6064, 6569), "60s", ifelse(cd_age %in% c(7074, 7579), "70s", ifelse(cd_age %in% c(8084, 8589), "80s", ifelse(cd_age %in% c(9094, 9599), "90s", "100+"))))))))))

# create another age category"age_cat2"
IDB_sub <- IDB_sub |>
  filter(!cd_age == "-3") |> # remove samples without information regarding age
  mutate(age_cat2 = if_else(cd_age %in% c(1600, 1700, 1800, 1900), "Under20", if_else(cd_age %in% c(6569, 7074, 7579, 8084, 8589, 9094, 9599, 9999) , "Elderly", "Adult")))
```

```{r}
# change values from Portugees to English
IDB_sub$sex <- recode(IDB_sub$sex, "FEMININO" = "female", "MASCULINO"= "male")

IDB_sub$cd_marit <- recode(IDB_sub$cd_marit, "1" = "Single", "3" = "Married", "5" = "Widowed", "7" = "Legally Separated", "9" = "Divorced") 
```


Accounting for the number of eligible voters in each row, create long format data frame.

```{r}
# The following code is too heavy for large data.
# IDB_sub_long <- data.frame()
# for (i in 1:nrow(IDB_sub)) {
#  row <- IDB_sub[i, ]
#  number <- row$num_eligvote
  
#  for (j in 1:number) {
#    IDB_sub_long <- rbind(IDB_sub_long, row)
#  }
# }


# Duplicate each row to create a new data frame
IDB_sub_long <- IDB_sub[rep(seq_len(nrow(IDB_sub)), IDB_sub$num_eligvote),]

# Reset row names
row.names(IDB_sub_long) <- NULL
```


Pick up top 10 cities with large participants
```{r}
top10_cities <- IDB_sub_long |> 
  group_by(name_muni) |>
  summarise(count = n(), .groups = "drop_last") |>
  arrange(desc(count))　|>
  head(10)

IDB_top10 <- IDB_sub_long |>
  filter(name_muni %in% top10_cities$name_muni)

IDB_top10$name_muni <- recode(IDB_top10$name_muni, "LISBOA" = "Lisbon", "NOVA YORK" = "New York", "MIL\xc3O" = "Milan", "NAG\xd3IA" = "Nagoya", "MADRI" = "Madrid", "MIAMI" = "Miami", 
"LONDRES" = "London", "T\xd3QUIO" = "Tokyo", "BOSTON" = "Boston", "PORTO" = "Porto") 

IDB_top10 |>
  group_by(name_muni) |>
  summarise(Total = n()) |>
  arrange(desc(Total))

```

Create graph
```{r}
# by cities by sex
IDB_top10 |>
  group_by(name_muni, sex) |>
  summarise(Total = n(), .groups = "drop") |>
  ggplot(aes(x = reorder(name_muni, -Total), y = Total, fill = sex)) +
  geom_col() +
  labs(title = "Voter Demographics in Major Cities by Gender",
       x = "Top 10 cities with the highest number of voters", 
       y = "Total number of voters") +
  scale_y_continuous(breaks = seq(0, max(46000), by = 5000)) +
  guides(fill = guide_legend(title = "Gender")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 20),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 14),
        axis.text.y = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 14))

```

```{r}
# by cities by marital status
IDB_top10 |>
  group_by(name_muni, cd_marit) |>
  summarise(Total = n(), .groups = "drop") |>
  ggplot(aes(x = reorder(name_muni, -Total), y = Total, fill = cd_marit)) +
  geom_col(position = "dodge") +
  labs(title = "Voter Demographics in Major Cities by Marital Status",
       x = "Top 10 cities with the highest number of voters", 
       y = "Total number of voters") +
  scale_y_continuous(breaks = seq(0, max(45000), by = 5000)) +
  guides(fill = guide_legend(title = "Marital Status")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 16),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
        axis.text.y = element_text(size = 12),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 12))
```

```{r}
# by cities by educational categories
IDB_top10 |>
  group_by(name_muni, educ_cat) |>
  summarise(Total = n(), .groups = "drop") |>
  ggplot(aes(x = reorder(name_muni, -Total), y = Total, fill = educ_cat)) +
  geom_col(position = "dodge") +
  labs(title = "Voter Demographics in Major Cities by Educational Status",
       x = "Top 10 cities with the highest number of voters", 
       y = "Total number of voters") +
  scale_y_continuous(breaks = seq(0, max(45000), by = 5000)) +
  guides(fill = guide_legend(title = "Educational Status")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 16),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
        axis.text.y = element_text(size = 12),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 10))
```
```{r}
# by cities by age categories
IDB_top10 |>
  group_by(name_muni, age_cat2) |>
  summarise(Total = n(), .groups = "drop") |>
  ggplot(aes(x = reorder(name_muni, -Total), y = Total, fill = age_cat2)) +
  geom_col() +
  labs(title = "Voter Demographics in Major Cities by Age Category",
       x = "Top 10 cities with the highest number of voters", 
       y = "Total number of voters") +
  scale_y_continuous(breaks = seq(0, max(45000), by = 5000)) +
  guides(fill = guide_legend(title = "Age Category")) +
  theme_minimal()　+
  theme(plot.title = element_text(size = 16),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
        axis.text.y = element_text(size = 12),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 12))
 
```

```{r}
# pie chart by age categories
IDB_top10 |>
  filter(name_muni == "Boston") |>
  ggplot(aes(x = "", fill = age_cat1)) +
  geom_bar(width = 1, position = "fill") +
  coord_polar(theta = "y") +
  labs(title = "Voter Demographics in Boston by Age Category",
       y = "Composition of Each Age Group") +
  guides(fill = guide_legend(title = "Age Category")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 16),  
        axis.title.x = element_text(size = 14),
        axis.title.y = element_blank(),
        legend.text = element_text(size = 14))
       
```

